# Generated by Django 5.2.4 on 2025-07-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='subscription_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Free'), (1, 'Basic'), (2, 'Pro'), (3, 'Enterprise')], default=0, help_text='0=Free, 1=Basic, 2=Pro, 3=Enterprise'),
        ),
    ]
