# Generated by Django 5.2.4 on 2025-07-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailuser_subscription_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='subscription_expires',
            field=models.DateTimeField(blank=True, help_text='When the current subscription level expries. Auto-resets to Free', null=True),
        ),
    ]
